'''
Author: Gricel Vazquez
Last reviewed: Feb 4, 2025

This script is used to run the entire process of generating PRISM/Evochecker files from JSON files.
It processes each JSON file in the input directory and generates the corresponding PRISM/Evochecker files.
No other .json files should be present in the input directory.
'''
import json
import sys
import arch.planning.json2pddl as json2pddl

import arch.planning.pddlplanner as pddlplanner
# import arch.planning.pddlplannercopy as pddlplanner
import arch.planning.plan2PMCfile as plan2PMCfile
import arch.planning.auxiliary as auxiliary
import os
import time
from arch.config.config import *
from arch.planningProblem.planningProblem import planning_problem

from arch.planning.planner_google_or.gen_google_problem import load as json_load
from arch.planning.planner_google_or.gen_google_problem import generate as google_generate


def main(problem_id, json_file_path):
    # Two problems supported:
    # CP-SAT (solved with Google OR-Tools) and PDDL (solved with ENHSP)
    # - check type:
    planning_type = check_json_file_4type(json_file_path)

    name_file = os.path.splitext(os.path.basename(json_file_path))[0] # get file name without extension
    INPUT_DIR = os.path.dirname(json_file_path)
    output_dir = os.path.join(INPUT_DIR, f"output_{name_file}_{problem_id}") # save to global variable

    # update global variable for problem output/input directory
    PROBLEM_OUTPUT_DIR[problem_id] = output_dir

    # Check if the JSON file exists
    if not os.path.isfile(json_file_path):
        raise FileNotFoundError(f"File not found: {json_file_path}")
        # sys.exit(1)
    else:
        if VERBOSE: print(f"[RunPlanner] Processing file: {json_file_path}")

    # Create output folder
    print(f"[RunPlanner] Creating output folder: {output_dir}")
    auxiliary.createFolder(output_dir)

    # Run the appropriate planner based on the problem type. Both planners now produce
    # only a plan.txt file (same text format for either), nothing else is returned.
    if planning_type == "google":
        print(f"[RunPlanner] Detected Google OR-Tools problem for {json_file_path}.")
        plan_file = _run_google_problem(problem_id, json_file_path, name_file, output_dir)

    elif planning_type == "pddl":
        print(f"[RunPlanner] Detected PDDL problem for {json_file_path}.")
        plan_file = _run_pddl_problem(problem_id, json_file_path, name_file, output_dir)

    # Load the original problem JSON once here (needed by createPRISMfile for probabilities,
    # costs, retries, steepness, etc. - same file used to generate either planner's problem).
    with open(json_file_path, 'r') as f:
        json_data = json.load(f)

    get_evochecker_and_prism_files(problem_id, json_file_path, name_file, output_dir, plan_file, json_data=json_data, population=POPULATION_SIZE, max_evals=MAX_EVALUATIONS)




def check_json_file_4type(json_file_path):
    with open(json_file_path, 'r') as f:
        data = json.load(f)
        if "task_graph" in data:
            return "google"
        return "pddl"
        

def _run_google_problem(problem_id, json_file_path, name_file, output_dir):
    '''
    Args:
        problem_id: Unique identifier for the planning problem.
        json_file_path: The path to the JSON file to be processed.
        name_file: File name without extension (shared with _run_pddl_problem).
        output_dir: Output directory for generated files (shared with _run_pddl_problem).
    Returns:
        The path to the generated plan file.
    '''
    # Process each JSON file in the input directory
    print("\n----Starting task planning...")

    try:
        # Load the Google OR-Tools problem from the JSON file
        print(f"[RunPlanner]: Loading Google OR-Tools problem for {name_file}...")
        json_problem = json_load(json_file_path)

        #create folder for Google OR-Tools (python instance) problem file
        googleORs_dir = os.path.join(output_dir, "googleORs")
        auxiliary.createFolder(googleORs_dir)

        # create Google OR-Tools (python) problem string
        google_problem_str =google_generate(json_problem, json_file_path)
        google_file = os.path.join(googleORs_dir, f"problem.py")
        with open(google_file, 'w') as f:
            f.write(google_problem_str)

        # run generated python file "google_file" containing the Google OR-Tools planning problem
        # it generates a plan.txt file
        google_globals = {"__name__": "__main__", "__file__": google_file}
        exec(compile(open(google_file).read(), google_file, 'exec'), google_globals)
        # read the plan.txt file generated by the Google OR-Tools problem.
        # NOTE: the generated solver (gen_google_problem.py) writes plan.txt to the PARENT of
        # its own directory (i.e. output_dir, not googleORs_dir) - see gen_google_problem.py's
        # `plan_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/plan.txt"`.
        plan_file = os.path.join(output_dir, "plan.txt")
        if not os.path.isfile(plan_file):
            raise FileNotFoundError(f"Plan file not found: {plan_file}. The Google OR-Tools problem may have failed to generate a plan.")

        return plan_file

        
        
        

        

    except FileNotFoundError as e:
        print(f"File not found: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error processing {json_file_path}: {e}")
        sys.exit(1)



def _run_pddl_problem(problem_id, json_file_path, name_file, output_dir):
    '''
    Args:
        problem_id: Unique identifier for the planning problem.
        json_file_path: The path to the JSON file to be processed.
        name_file: File name without extension (shared with _run_google_problem).
        output_dir: Output directory for generated files (shared with _run_google_problem).
    Returns:
        The path to the generated plan file.
    '''
    # Process each JSON file in the input directory
    print("\n----Starting task planning...")

    # Variables specific to PDDL planning
    population = POPULATION_SIZE
    max_evals = MAX_EVALUATIONS
    num_runs = NUM_TIMED_RUNS

    # Create log file for elapsed time
    time_log_file = output_dir + "/" + f"time-log-planner-{num_runs}runs.txt"
    auxiliary.createFile(time_log_file) 
    
    
    for run in range(1, num_runs+1):
        start_time = time.time()
                        
        # PDDL file names
        file_domain = FILE_DOMAIN_PDDL
        file_problem = FILE_PROBLEM_PDDL

        try:
            
            # Generate PDDL files
            if VERBOSE: print(f"[RunPlanner]: Generating PDDL files for {name_file}-{run}...")
            json_data = json2pddl.main(json_file_path, output_dir, file_domain, file_problem)
            
            # Import PDDL problem
            print(f"[RunPlanner]: Importing PDDL problem for {name_file}-{run} from {output_dir}")
            problem = pddlplanner.importPDDLproblem(output_dir, file_domain, file_problem)
            
            # Run PDDL planner
            print(f"[RunPlanner]: Running PDDL planner for {name_file}-{run}...")
            # TODO: currently timeout is set to 0 to avoid running TempestEngine
            # if need to allow for multiple plans with timeout > 0, see headless version in GitHub branch for multiple plans
            tempestEngineTimeout = 0 # in seconds

            # Run the planner and get the plans found
            plans_found = pddlplanner.runPlanner(file_domain, file_problem, output_dir, json_data, timeout=tempestEngineTimeout, headless=False)
            
            if not plans_found or len(plans_found) == 0:
                raise RuntimeError(f"No plans found for problem '{name_file}'. ENHSP may have failed — check Java 17+ is installed and the problem definition is valid.")

            # Only the first plan is used
            plan = plans_found[0]
            print(f"CHECK --------------- {plan}")

            # Log with elapsed time (for the current run)
            end_time = time.time()
            elapsed_time = end_time - start_time
            print(f"[RunPlanner]: Elapsed time for {name_file}-{run}: {elapsed_time:.2f} seconds")
            with open(time_log_file, 'a') as f:
                f.write(f"[RunPlanner]: Time elapsed for {name_file}-{run}: {elapsed_time:.2f} seconds\n")
        except FileNotFoundError as e:
            print(f"File not found: {e}")
            sys.exit(1)
        except Exception as e:
            print(f"Error processing {json_file_path} on Run {run}: {e}")
            sys.exit(1)

    # pddlplanner.runPlanner() writes plan.txt to output_dir on every run, overwriting it each
    # time; after NUM_TIMED_RUNS runs (for benchmarking), what's on disk is the last run's plan.
    return os.path.join(output_dir, "plan.txt")



def get_evochecker_and_prism_files(problem_id, json_file_path, name_file, output_dir, plan_file, json_data, population, max_evals):
    '''
    Generate PRISM and EvoChecker files from a plan.txt file. Both planners (Google OR-Tools
    and PDDL/TEMPest) now write that same plan.txt text format, so this is called once from
    main(), uniformly, after whichever planner produced plan_file.

    Args:
        plan_file: path to the plan.txt file to read (NOT a unified_planning plan object).
        json_data: the parsed problem JSON (probabilities, costs, retries, steepness, etc.
            are looked up from here - see plan2PMCfile._extract_uncertainty_data and
            planningProblem.get_steepness).
    Returns:
        The path to the EvoChecker config.properties file.
    '''
    start_time = time.time()

    # Initialise the steepness map (createPRISMfile -> planning_problem.get_steepness relies on
    # this having been built from json_data first; this used to happen inside
    # pddlplanner.savePRISMEvochekerFiles, which is no longer called from the active path).
    planning_problem.set_from_data(json_data, output_dir)

    # Generate PRISM/Evochecker files from the plan.txt file
    print(f"[RunPlanner]: Generating Evochecker files for {name_file}...")
    evo_config_file = plan2PMCfile.createPRISMfile(output_dir, name_file, plan_file, json_data, evoChecker=True, population=population, max_evals=max_evals)
    print(f"[RunPlanner]: Generating PRISM file for {name_file}...")
    plan2PMCfile.createPRISMfile(output_dir, name_file, plan_file, json_data, evoChecker=False, population=population, max_evals=max_evals)

    elapsed_time = time.time() - start_time
    print(f"[RunPlanner]: Elapsed time generating Evochecker/PRISM files for {name_file}: {elapsed_time:.2f} seconds")

    return evo_config_file

